"""Added recurrence field to expenses

Revision ID: f59bdc5a7ce9
Revises: 166bde02b73e
Create Date: 2025-02-16 23:32:55.098843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59bdc5a7ce9'
down_revision = '166bde02b73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
